@startuml
left to right direction

package "Presentation" {
    component UI
}

package "Domain" {
    component "Strategy IL" as StrategyIL
}

package "Application" {
    interface Backtester
    interface "Code Generator" as CodeGen
}

package "Infrastructure" {
    component "Pyodide Adapter" as Pyodide
    component "Backtrader Generator" as BacktraderGen
    component "PineScript Generator" as PineGen
    component "MQL Generator" as MQLGen
}

UI ..> Backtester
UI ..> CodeGen

Backtester ..> CodeGen
CodeGen ..> StrategyIL


Backtester -- Pyodide
CodeGen -- BacktraderGen
CodeGen -- PineGen
CodeGen -- MQLGen

@enduml
