// Auto-generated from backtrader indicator reference.
// Source: https://r.jina.ai/https://www.backtrader.com/docu/indautoref/

export const BACKTRADER_INDICATOR_PARAMS: Record<string, string[]> = {
  AccelerationDecelerationOscillator: [],
  Accum: ['seed'],
  AdaptiveMovingAverage: ['period', 'fast', 'slow'],
  AdaptiveMovingAverageEnvelope: ['period', 'fast', 'slow', 'perc'],
  AdaptiveMovingAverageOscillator: ['period', 'fast', 'slow'],
  AllN: ['period'],
  AnyN: ['period'],
  ApplyN: ['period', 'func'],
  AroonDown: ['period', 'upperband', 'lowerband'],
  AroonOscillator: ['period', 'upperband', 'lowerband'],
  AroonUp: ['period', 'upperband', 'lowerband'],
  AroonUpDown: ['period', 'upperband', 'lowerband'],
  AroonUpDownOscillator: ['period', 'upperband', 'lowerband'],
  Average: ['period'],
  AverageDirectionalMovementIndex: ['period', 'movav'],
  AverageDirectionalMovementIndexRating: ['period', 'movav'],
  AverageTrueRange: ['period', 'movav'],
  AwesomeOscillator: ['fast', 'slow', 'movav'],
  BaseApplyN: ['period', 'func'],
  BollingerBands: ['period', 'devfactor', 'movav'],
  BollingerBandsPct: ['period', 'devfactor', 'movav'],
  CointN: ['period', 'regression'],
  CommodityChannelIndex: [
    'period',
    'factor',
    'movav',
    'upperband',
    'lowerband',
  ],
  CrossDown: [],
  CrossOver: [],
  CrossUp: [],
  DV2: ['period', 'maperiod', '_movav'],
  DemarkPivotPoint: [
    'open',
    'close',
    '_autoplot',
    'level1',
    'level2',
    'level3',
  ],
  DetrendedPriceOscillator: ['period', 'movav'],
  DicksonMovingAverage: ['period', 'gainlimit', 'hperiod', '_movav', '_hma'],
  DicksonMovingAverageEnvelope: [
    'period',
    'gainlimit',
    'hperiod',
    '_movav',
    '_hma',
    'perc',
  ],
  DicksonMovingAverageOscillator: [
    'period',
    'gainlimit',
    'hperiod',
    '_movav',
    '_hma',
  ],
  DirectionalIndicator: ['period', 'movav'],
  DirectionalMovement: ['period', 'movav'],
  DirectionalMovementIndex: ['period', 'movav'],
  DoubleExponentialMovingAverage: ['period', '_movav'],
  DoubleExponentialMovingAverageEnvelope: ['period', '_movav', 'perc'],
  DoubleExponentialMovingAverageOscillator: ['period', '_movav'],
  DownDay: ['period'],
  DownDayBool: ['period'],
  DownMove: [],
  Envelope: ['perc'],
  ExponentialMovingAverage: ['period'],
  ExponentialMovingAverageEnvelope: ['period', 'perc'],
  ExponentialMovingAverageOscillator: ['period'],
  ExponentialSmoothing: ['period', 'alpha'],
  ExponentialSmoothingDynamic: ['period', 'alpha'],
  FibonacciPivotPoint: [
    'open',
    'close',
    '_autoplot',
    'level1',
    'level2',
    'level3',
  ],
  FindFirstIndex: ['period', '_evalfunc'],
  FindFirstIndexHighest: ['period', '_evalfunc'],
  FindFirstIndexLowest: ['period', '_evalfunc'],
  FindLastIndex: ['period', '_evalfunc'],
  FindLastIndexHighest: ['period', '_evalfunc'],
  FindLastIndexLowest: ['period', '_evalfunc'],
  Fractal: ['period', 'bardist', 'shift_to_potential_fractal'],
  HeikinAshi: [],
  Highest: ['period'],
  HullMovingAverage: ['period', '_movav'],
  HullMovingAverageEnvelope: ['period', '_movav', 'perc'],
  HullMovingAverageOscillator: ['period', '_movav'],
  HurstExponent: ['period', 'lag_start', 'lag_end'],
  Ichimoku: ['tenkan', 'kijun', 'senkou', 'senkou_lead', 'chikou'],
  KnowSureThing: [
    'rp1',
    'rp2',
    'rp3',
    'rp4',
    'rma1',
    'rma2',
    'rma3',
    'rma4',
    'rsignal',
    'rfactors',
    '_rmovav',
    '_smovav',
  ],
  LaguerreFilter: ['period', 'gamma'],
  LaguerreRSI: ['period', 'gamma'],
  LinePlotterIndicator: [],
  Lowest: ['period'],
  MACD: ['period_me1', 'period_me2', 'period_signal', 'movav'],
  MACDHisto: ['period_me1', 'period_me2', 'period_signal', 'movav'],
  MeanDeviation: ['period', 'movav'],
  MinusDirectionalIndicator: ['period', 'movav'],
  Momentum: ['period'],
  MomentumOscillator: ['period', 'band'],
  MovingAverageBase: ['period'],
  MovingAverageSimple: ['period'],
  MovingAverageSimpleEnvelope: ['period', 'perc'],
  MovingAverageSimpleOscillator: ['period'],
  NonZeroDifference: [],
  OLS_BetaN: ['period'],
  OLS_Slope_InterceptN: ['period', 'prepend_constant'],
  OLS_TransformationN: ['period'],
  OperationN: ['period'],
  Oscillator: [],
  OscillatorMixIn: [],
  ParabolicSAR: ['period', 'af', 'afmax'],
  PercentChange: ['period'],
  PercentRank: ['period', 'func'],
  PercentagePriceOscillator: ['period1', 'period2', '_movav', 'period_signal'],
  PercentagePriceOscillatorShort: [
    'period1',
    'period2',
    '_movav',
    'period_signal',
  ],
  PeriodN: ['period'],
  PivotPoint: ['open', 'close', '_autoplot'],
  PlusDirectionalIndicator: ['period', 'movav'],
  PrettyGoodOscillator: ['period', '_movav'],
  PriceOscillator: ['period1', 'period2', '_movav'],
  RSI_EMA: [
    'period',
    'movav',
    'upperband',
    'lowerband',
    'safediv',
    'safehigh',
    'safelow',
    'lookback',
  ],
  RSI_SMA: [
    'period',
    'movav',
    'upperband',
    'lowerband',
    'safediv',
    'safehigh',
    'safelow',
    'lookback',
  ],
  RSI_Safe: [
    'period',
    'movav',
    'upperband',
    'lowerband',
    'safediv',
    'safehigh',
    'safelow',
    'lookback',
  ],
  RateOfChange: ['period'],
  RateOfChange100: ['period'],
  ReduceN: ['period'],
  RelativeMomentumIndex: [
    'period',
    'movav',
    'upperband',
    'lowerband',
    'safediv',
    'safehigh',
    'safelow',
    'lookback',
  ],
  RelativeStrengthIndex: [
    'period',
    'movav',
    'upperband',
    'lowerband',
    'safediv',
    'safehigh',
    'safelow',
    'lookback',
  ],
  Signal: [],
  SmoothedMovingAverage: ['period'],
  SmoothedMovingAverageEnvelope: ['period', 'perc'],
  SmoothedMovingAverageOscillator: ['period'],
  StandardDeviation: ['period', 'movav', 'safepow'],
  Stochastic: [
    'period',
    'period_dfast',
    'movav',
    'upperband',
    'lowerband',
    'safediv',
    'safezero',
    'period_dslow',
  ],
  StochasticFast: [
    'period',
    'period_dfast',
    'movav',
    'upperband',
    'lowerband',
    'safediv',
    'safezero',
  ],
  StochasticFull: [
    'period',
    'period_dfast',
    'movav',
    'upperband',
    'lowerband',
    'safediv',
    'safezero',
    'period_dslow',
  ],
  SumN: ['period'],
  TripleExponentialMovingAverage: ['period', '_movav'],
  TripleExponentialMovingAverageEnvelope: ['period', '_movav', 'perc'],
  TripleExponentialMovingAverageOscillator: ['period', '_movav'],
  Trix: ['period', '_rocperiod', '_movav'],
  TrixSignal: ['period', '_rocperiod', '_movav', 'sigperiod'],
  TrueHigh: [],
  TrueLow: [],
  TrueRange: [],
  TrueStrengthIndicator: ['period1', 'period2', 'pchange', '_movav'],
  UltimateOscillator: ['p1', 'p2', 'p3', 'upperband', 'lowerband'],
  UpDay: ['period'],
  UpDayBool: ['period'],
  UpMove: [],
  Vortex: ['period'],
  WeightedAverage: ['period', 'coef', 'weights'],
  WeightedMovingAverage: ['period'],
  WeightedMovingAverageEnvelope: ['period', 'perc'],
  WeightedMovingAverageOscillator: ['period'],
  WilliamsAD: [],
  WilliamsR: ['period', 'upperband', 'lowerband'],
  ZeroLagExponentialMovingAverage: ['period', '_movav'],
  ZeroLagExponentialMovingAverageEnvelope: ['period', '_movav', 'perc'],
  ZeroLagExponentialMovingAverageOscillator: ['period', '_movav'],
  ZeroLagIndicator: ['period', 'gainlimit', '_movav'],
  ZeroLagIndicatorEnvelope: ['period', 'gainlimit', '_movav', 'perc'],
  ZeroLagIndicatorOscillator: ['period', 'gainlimit', '_movav'],
  haDelta: ['period', 'movav', 'autoheikin'],
};

export const BACKTRADER_INDICATOR_ALIASES: Record<string, string> = {
  accelerationdecelerationoscillator: 'AccelerationDecelerationOscillator',
  accum: 'Accum',
  adaptivemovingaverage: 'AdaptiveMovingAverage',
  adaptivemovingaverageenvelope: 'AdaptiveMovingAverageEnvelope',
  adaptivemovingaverageoscillator: 'AdaptiveMovingAverageOscillator',
  alln: 'AllN',
  anyn: 'AnyN',
  applyn: 'ApplyN',
  aroondown: 'AroonDown',
  aroonoscillator: 'AroonOscillator',
  aroonup: 'AroonUp',
  aroonupdown: 'AroonUpDown',
  aroonupdownoscillator: 'AroonUpDownOscillator',
  average: 'Average',
  averagedirectionalmovementindex: 'AverageDirectionalMovementIndex',
  averagedirectionalmovementindexrating:
    'AverageDirectionalMovementIndexRating',
  averagetruerange: 'AverageTrueRange',
  awesomeoscillator: 'AwesomeOscillator',
  baseapplyn: 'BaseApplyN',
  bollingerbands: 'BollingerBands',
  bollingerbandspct: 'BollingerBandsPct',
  cointn: 'CointN',
  commoditychannelindex: 'CommodityChannelIndex',
  crossdown: 'CrossDown',
  crossover: 'CrossOver',
  crossup: 'CrossUp',
  dv2: 'DV2',
  demarkpivotpoint: 'DemarkPivotPoint',
  detrendedpriceoscillator: 'DetrendedPriceOscillator',
  dicksonmovingaverage: 'DicksonMovingAverage',
  dicksonmovingaverageenvelope: 'DicksonMovingAverageEnvelope',
  dicksonmovingaverageoscillator: 'DicksonMovingAverageOscillator',
  directionalindicator: 'DirectionalIndicator',
  directionalmovement: 'DirectionalMovement',
  directionalmovementindex: 'DirectionalMovementIndex',
  doubleexponentialmovingaverage: 'DoubleExponentialMovingAverage',
  doubleexponentialmovingaverageenvelope:
    'DoubleExponentialMovingAverageEnvelope',
  doubleexponentialmovingaverageoscillator:
    'DoubleExponentialMovingAverageOscillator',
  downday: 'DownDay',
  downdaybool: 'DownDayBool',
  downmove: 'DownMove',
  envelope: 'Envelope',
  exponentialmovingaverage: 'ExponentialMovingAverage',
  exponentialmovingaverageenvelope: 'ExponentialMovingAverageEnvelope',
  exponentialmovingaverageoscillator: 'ExponentialMovingAverageOscillator',
  exponentialsmoothing: 'ExponentialSmoothing',
  exponentialsmoothingdynamic: 'ExponentialSmoothingDynamic',
  fibonaccipivotpoint: 'FibonacciPivotPoint',
  findfirstindex: 'FindFirstIndex',
  findfirstindexhighest: 'FindFirstIndexHighest',
  findfirstindexlowest: 'FindFirstIndexLowest',
  findlastindex: 'FindLastIndex',
  findlastindexhighest: 'FindLastIndexHighest',
  findlastindexlowest: 'FindLastIndexLowest',
  fractal: 'Fractal',
  heikinashi: 'HeikinAshi',
  highest: 'Highest',
  hullmovingaverage: 'HullMovingAverage',
  hullmovingaverageenvelope: 'HullMovingAverageEnvelope',
  hullmovingaverageoscillator: 'HullMovingAverageOscillator',
  hurstexponent: 'HurstExponent',
  ichimoku: 'Ichimoku',
  knowsurething: 'KnowSureThing',
  laguerrefilter: 'LaguerreFilter',
  laguerrersi: 'LaguerreRSI',
  lineplotterindicator: 'LinePlotterIndicator',
  lowest: 'Lowest',
  macd: 'MACD',
  macdhisto: 'MACDHisto',
  meandeviation: 'MeanDeviation',
  minusdirectionalindicator: 'MinusDirectionalIndicator',
  momentum: 'Momentum',
  momentumoscillator: 'MomentumOscillator',
  movingaveragebase: 'MovingAverageBase',
  movingaveragesimple: 'MovingAverageSimple',
  movingaveragesimpleenvelope: 'MovingAverageSimpleEnvelope',
  movingaveragesimpleoscillator: 'MovingAverageSimpleOscillator',
  nonzerodifference: 'NonZeroDifference',
  ols_betan: 'OLS_BetaN',
  ols_slope_interceptn: 'OLS_Slope_InterceptN',
  ols_transformationn: 'OLS_TransformationN',
  operationn: 'OperationN',
  oscillator: 'Oscillator',
  oscillatormixin: 'OscillatorMixIn',
  parabolicsar: 'ParabolicSAR',
  percentchange: 'PercentChange',
  percentrank: 'PercentRank',
  percentagepriceoscillator: 'PercentagePriceOscillator',
  percentagepriceoscillatorshort: 'PercentagePriceOscillatorShort',
  periodn: 'PeriodN',
  pivotpoint: 'PivotPoint',
  plusdirectionalindicator: 'PlusDirectionalIndicator',
  prettygoodoscillator: 'PrettyGoodOscillator',
  priceoscillator: 'PriceOscillator',
  rsi_ema: 'RSI_EMA',
  rsi_sma: 'RSI_SMA',
  rsi_safe: 'RSI_Safe',
  rateofchange: 'RateOfChange',
  rateofchange100: 'RateOfChange100',
  reducen: 'ReduceN',
  relativemomentumindex: 'RelativeMomentumIndex',
  relativestrengthindex: 'RelativeStrengthIndex',
  signal: 'Signal',
  smoothedmovingaverage: 'SmoothedMovingAverage',
  smoothedmovingaverageenvelope: 'SmoothedMovingAverageEnvelope',
  smoothedmovingaverageoscillator: 'SmoothedMovingAverageOscillator',
  standarddeviation: 'StandardDeviation',
  stochastic: 'Stochastic',
  stochasticfast: 'StochasticFast',
  stochasticfull: 'StochasticFull',
  sumn: 'SumN',
  tripleexponentialmovingaverage: 'TripleExponentialMovingAverage',
  tripleexponentialmovingaverageenvelope:
    'TripleExponentialMovingAverageEnvelope',
  tripleexponentialmovingaverageoscillator:
    'TripleExponentialMovingAverageOscillator',
  trix: 'Trix',
  trixsignal: 'TrixSignal',
  truehigh: 'TrueHigh',
  truelow: 'TrueLow',
  truerange: 'TrueRange',
  truestrengthindicator: 'TrueStrengthIndicator',
  ultimateoscillator: 'UltimateOscillator',
  upday: 'UpDay',
  updaybool: 'UpDayBool',
  upmove: 'UpMove',
  vortex: 'Vortex',
  weightedaverage: 'WeightedAverage',
  weightedmovingaverage: 'WeightedMovingAverage',
  weightedmovingaverageenvelope: 'WeightedMovingAverageEnvelope',
  weightedmovingaverageoscillator: 'WeightedMovingAverageOscillator',
  williamsad: 'WilliamsAD',
  williamsr: 'WilliamsR',
  zerolagexponentialmovingaverage: 'ZeroLagExponentialMovingAverage',
  zerolagexponentialmovingaverageenvelope:
    'ZeroLagExponentialMovingAverageEnvelope',
  zerolagexponentialmovingaverageoscillator:
    'ZeroLagExponentialMovingAverageOscillator',
  zerolagindicator: 'ZeroLagIndicator',
  zerolagindicatorenvelope: 'ZeroLagIndicatorEnvelope',
  zerolagindicatoroscillator: 'ZeroLagIndicatorOscillator',
  hadelta: 'haDelta',
};
